name: Farcaster bot cron

on:
  schedule:
    - cron: */30 * * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Crawl Farcster then tweet
        run: curl -s -X POST "https://bot-monorepo.vercel.app/api/farcaster/crawl"